# Generated by Django 4.1.2 on 2022-10-14 17:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_category_name_de_category_name_es_category_name_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, upload_to="marker/", verbose_name="Image"
            ),
        ),
    ]
