# Generated by Django 4.1.2 on 2022-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_marker_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("cadetblue", "cadetblue"),
                    ("green", "green"),
                    ("blue", "blue"),
                    ("red", "red"),
                    ("purple", "purple"),
                    ("lightgreen", "lightgreen"),
                    ("darkblue", "darkblue"),
                    ("orange", "orange"),
                    ("gray", "gray"),
                    ("pink", "pink"),
                    ("lightblue", "lightblue"),
                    ("lightgray", "lightgray"),
                    ("darkgreen", "darkgreen"),
                    ("darkred", "darkred"),
                    ("black", "black"),
                ],
                max_length=50,
                verbose_name="Color",
            ),
        ),
    ]
