# Generated by Django 4.0.8 on 2022-11-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Comment'),
        ),
    ]
