# Generated by Django 4.0.8 on 2022-11-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_alter_marker_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='valid_till',
            field=models.DateField(blank=True, null=True, verbose_name='Valid till'),
        ),
    ]
