exclude: ^archive/.*|.*/test-data/.*|.*/vendor/.*|.*\.svg$
minimum_pre_commit_version: "2.15.0"
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.0.1"
    hooks:
      - id: "check-case-conflict"
      - id: "mixed-line-ending"
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-json"
      - id: "check-yaml"
      - id: "check-added-large-files"
      - id: "detect-aws-credentials"
        args: [ "--allow-missing-credentials" ]
      - id: "detect-private-key"

  - repo: "https://github.com/psf/black"
    rev: "21.7b0"
    hooks:
      - id: "black"
        name: "Format code (black)"
        language_version: "python3.10"
        exclude: ^docs/.*$

  - repo: "https://github.com/PyCQA/isort"
    rev: "5.10.1"
    hooks:
      - id: "isort"
        args: ["-m", "3", "-tc"]
        name: "Format code (isort)"
        language_version: "python3.9"
        additional_dependencies:
          - "isort==5.10.1"
          - "toml==0.10.2"
        types: ["python"]

  - repo: "https://github.com/myint/autoflake"
    rev: v1.4
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variable"]
